name: Run Tests

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  run-tests:
    name: Run tests using Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6.0"]
    steps:
      - name: Install Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build
        run: swift build -v

      - name: Run Tests
        run: swift test -v
